service: hako-puppeteer
provider:
  name: aws
  region: ap-northeast-1
  profile: ${self:custom.awsProfile.${self:custom.stage}}
  environment: ${file(./env.yml):${self:custom.stage}}
  runtime: nodejs12.x

custom:
  stage: ${opt:stage, self:provider.stage}
  awsProfile:
    local: myaws
    dev: myaws
    prod: hako
  # webpack:
  #   webpackConfig: ./webpack.config.js
  #   includeModules: true
  #   packager: yarn

plugins:
  - serverless-offline
  - serverless-plugin-chrome
  # - serverless-webpack

package:
  individually: false
  exclude:
    - node_modules/chrome-aws-lambda/**
    - node_modules/puppeteer/.local-chromium/**

functions:
  puppeteer:
    handler: handler.puppeteer
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: puppeteer/html
          method: get
          integration: lambda-proxy
      - http:
          path: puppeteer/screenshot/heatmap
          method: get
          integration: lambda-proxy
